Get full RPC response in cli function
Juniper/py-junos-eznc pull request #1315
Opened 2024-07-23 19:08 UTC by dkaplan1

`junos-eznc`'s `execute` function only returns the first child element, described in https://github.com/Juniper/py-junos-eznc/blob/a64698b280fb717730dddf75a2d4d8cacb2e4775/lib/jnpr/junos/device.py#L896-L901
Normally this isn't an issue, since commands return the full payload in one `<output>` as part of a `<rpc-reply>` i.e.
```
<rpc-reply message-id="xxx"><output>
Slot 0   Online       xxx
  PIC 0  Online       xxx
  PIC 1  Online       xxx
Slot 1   Online       xxx
  PIC 0  Online       xxx
  PIC 1  Online       xxx
</output></rpc-reply>
```
However, for some commands, like `show system core-dumps`, the `<rpc-reply>` contains multiple `<output>`s.
```
<rpc-reply message-id="urn:uuid:xxx"><output>
/var/crash/*core*: No such file or directory
</output><output>
/var/tmp/*core*: No such file or directory
</output><output>
/var/tmp/pics/*core*: No such file or directory
</output><output>
/var/crash/kernel.*: No such file or directory
</output><output>
/var/jails/rest-api/tmp/*core*: No such file or directory
</output><output>
/tftpboot/corefiles/*core*: No such file or directory
</output></rpc-reply>
```
In these cases, only selecting the first element means that we only select 
```
<output>
/var/crash/*core*: No such file or directory
</output>
```
and `cli` returns just 
```
/var/crash/*core*: No such file or directory
```
instead of the full output.

To fix this I'm proposing to get the parent of output message (if one exists) so that the full output of the command is returned.

2024-07-31 04:44 UTC, chidanandpujar commented
Hi @dkaplan1 
    Thanks for the pull request.
    Please find the review comments.

   we are seeing one warning for following line of code.
 if rsp.tag in "output" and rsp.getparent():

can be changed to 
if rsp.tag in "output" and rsp.getparent() is not None:

Please check if it can be fixed, otherwise the cli response has the full response.


/root/pyez_release_272/venv/lib/python3.12/site-packages/junos_eznc-2.7.1+9.ga64698b2-py3.12.egg/jnpr/junos/device.py:738: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
  if rsp.tag in "output" and rsp.getparent():

/var/crash/*core*: No such file or directory

/var/tmp/*core*: No such file or directory

/var/tmp/pics/*core*: No such file or directory

/var/crash/kernel.*: No such file or directory

/var/jails/rest-api/tmp/*core*: No such file or directory

/tftpboot/corefiles/*core*: No such file or directory



 python cli_test.py 


                     Temp  CPU Utilization (%)   CPU Utilization (%)  Memory    Utilization (%)
Slot State            (C)  Total  Interrupt      1min   5min   15min  DRAM (MB) Heap     Buffer
  0  Online           Testing   4         0        3      3      3    511        34          0
  1  Empty           
  2  Empty           
  3  Empty           
  4  Empty           
  5  Empty           
  6  Empty           
  7  Empty           
  8  Empty           
  9  Empty           
 10  Empty           
 11  Empty           


python cli_test.py 
/root/pyez_release_272/venv/lib/python3.12/site-packages/paramiko/pkey.py:100: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "cipher": algorithms.TripleDES,
/root/pyez_release_272/venv/lib/python3.12/site-packages/paramiko/transport.py:271: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "class": algorithms.TripleDES,

/var/crash/*core*: No such file or directory

/var/tmp/*core*: No such file or directory

/var/tmp/pics/*core*: No such file or directory

/var/crash/kernel.*: No such file or directory

/var/jails/rest-api/tmp/*core*: No such file or directory

/tftpboot/corefiles/*core*: No such file or directory

Thanks 
Chidanand

2024-07-31 04:48 UTC, chidanandpujar requested changes
Please check if we can change the following line from 
if rsp.tag == "output" and rsp.getparent(): 

to
if rsp.tag in "output" and rsp.getparent() is not None:

2024-07-31 17:06 UTC, dkaplan1 commented
Thanks for the review @chidanandpujar, updated.

2024-08-01 03:22 UTC, chidanandpujar commented
Hi @dkaplan1 
   Thanks for taking care of review comments.
    Fix looks to be working fine .

```
 python cli_test.py 
/root/pyez_release_272/venv/lib/python3.12/site-packages/paramiko/pkey.py:100: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "cipher": algorithms.TripleDES,
/root/pyez_release_272/venv/lib/python3.12/site-packages/paramiko/transport.py:271: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "class": algorithms.TripleDES,

/var/crash/*core*: No such file or directory

/var/tmp/*core*: No such file or directory

/var/tmp/pics/*core*: No such file or directory

/var/crash/kernel.*: No such file or directory

/var/jails/rest-api/tmp/*core*: No such file or directory

/tftpboot/corefiles/*core*: No such file or directory


                     Temp  CPU Utilization (%)   CPU Utilization (%)  Memory    Utilization (%)
Slot State            (C)  Total  Interrupt      1min   5min   15min  DRAM (MB) Heap     Buffer
  0  Online           Testing   3         0        3      3      3    511        34          0
  1  Empty           
  2  Empty           
  3  Empty           
  4  Empty           
  5  Empty           
  6  Empty           
  7  Empty           
  8  Empty           
  9  Empty           
 10  Empty           
 11  Empty           
```

Thanks
Chidanand

2024-08-01 03:22 UTC, chidanandpujar approved these changes
looks good

2024-10-10 07:38 UTC, chidanandpujar commented
Validated functional tests: looks good.

(venv) root@masterhost:~/pyez_release_test1/py-junos-eznc# nose2 -v -c nose2.cfg 
test_load_config_jinja2 (tests.functional.test_config.TestCore.test_load_config_jinja2) ... ok
test_load_config_jinja2_template (tests.functional.test_config.TestCore.test_load_config_jinja2_template) ... ok
test_load_config_json (tests.functional.test_config.TestCore.test_load_config_json) ... ok
test_load_config_set (tests.functional.test_config.TestCore.test_load_config_set) ... ok
test_load_config_text (tests.functional.test_config.TestCore.test_load_config_text) ... ok
test_load_config_xml (tests.functional.test_config.TestCore.test_load_config_xml) ... ok
test_config_exception (tests.functional.test_exception.TestUtilFs.test_config_exception) ... ok
test_device_rpc_timeout (tests.functional.test_exception.TestUtilFs.test_device_rpc_timeout) ... ok
test_exception (tests.functional.test_exception.TestUtilFs.test_exception) ... ok
test_exception_commitError (tests.functional.test_exception.TestUtilFs.test_exception_commitError) ... ok
test_exception_commitError_commitCheck (tests.functional.test_exception.TestUtilFs.test_exception_commitError_commitCheck) ... ok
test_exception_severity (tests.functional.test_exception.TestUtilFs.test_exception_severity) ... ok
test_FS_checksum (tests.functional.test_exception.TestUtilFs.test_FS_checksum) ... ok
test_load_exception (tests.functional.test_exception.TestUtilFs.test_load_exception) ... ok
test_lock_exception (tests.functional.test_exception.TestUtilFs.test_lock_exception) ... ok
test_rescue_action (tests.functional.test_exception.TestUtilFs.test_rescue_action) ... ok
test_rollback_id (tests.functional.test_exception.TestUtilFs.test_rollback_id) ... ok
test_rpc_exception (tests.functional.test_exception.TestUtilFs.test_rpc_exception) ... ok
test_rpc_exist (tests.functional.test_exception.TestUtilFs.test_rpc_exist) ... ok
test_rpc_load_extension (tests.functional.test_exception.TestUtilFs.test_rpc_load_extension) ... ERROR
test_rpc_no_format (tests.functional.test_exception.TestUtilFs.test_rpc_no_format) ... ok
test_rpc_set_override (tests.functional.test_exception.TestUtilFs.test_rpc_set_override) ... ok
test_unlock_exception (tests.functional.test_exception.TestUtilFs.test_unlock_exception) ... ok
test_device_rpc (tests.functional.test_rpc.TestCore.test_device_rpc) ... ok
test_device_rpc_format_text (tests.functional.test_rpc.TestCore.test_device_rpc_format_text) ... ok
test_device_rpc_timeout (tests.functional.test_rpc.TestCore.test_device_rpc_timeout) ... ok
test_display_xml_rpc (tests.functional.test_rpc.TestCore.test_display_xml_rpc) ... ok
test_getConfig (tests.functional.test_rpc.TestCore.test_getConfig) ... ok
test_interface_terse_text (tests.functional.test_rpc.TestCore.test_interface_terse_text) ... ok
test_route_information (tests.functional.test_rpc.TestCore.test_route_information) ... ok
test_rpc_get_interface_information_mtun (tests.functional.test_rpc.TestCore.test_rpc_get_interface_information_mtun) ... ok
test_scp_put (tests.functional.test_file_scp.test.test_scp_put) ... 10.220.2.221: b'scp_file.txt': 1 / 1 (100%)
ok
test_scp_put_file_get (tests.functional.test_file_scp.test.test_scp_put_file_get) ... ok
test_arp_table (tests.functional.test_table_present.test_table.test_arp_table) ... ['56:03:02:00:25:06', '00:01:00:02:00:03', 'bc:24:11:5d:8d:1d', 'bc:24:11:33:49:b3', '54:04:0a:dc:01:26', '54:04:0a:dc:01:29', '54:04:0a:dc:01:3c', '54:04:0a:dc:01:51', '54:04:0a:dc:01:65', '54:04:0a:dc:01:6f', '54:04:0a:dc:01:70', '54:04:0a:dc:01:79', '54:04:0a:dc:01:95', '54:04:0a:dc:01:b8', '54:04:0a:dc:01:c3', '54:04:0a:dc:01:c6', '54:04:0a:dc:01:e5', '54:04:0a:dc:01:fa', '54:04:0a:dc:01:fd', '54:04:0a:dc:02:04', '54:04:0a:dc:02:0d', '54:04:0a:dc:02:17', '54:04:0a:dc:02:24', '54:04:0a:dc:02:27', '54:04:0a:dc:02:2a', '54:04:0a:dc:02:eb', '54:04:0a:dc:02:fd', '54:04:0a:dc:03:0f', '54:04:0a:dc:03:12', '54:04:0a:dc:03:22', '54:04:0a:dc:03:23', '54:04:0a:dc:03:a2', '54:04:0a:dc:03:a4', '54:04:0a:dc:03:b8', '54:04:0a:dc:03:b9', '54:04:0a:dc:03:c2', '54:04:0a:dc:04:06', '54:04:0a:dc:04:08', '54:04:0a:dc:04:22', '54:04:0a:dc:04:27', '54:04:0a:dc:04:90', '54:04:0a:dc:04:9b', '54:04:0a:dc:04:a0', '54:04:0a:dc:04:c7', '54:04:0a:dc:04:c8', '54:04:0a:dc:04:e5', '54:04:0a:dc:04:ee', '54:04:0a:dc:04:fb', '54:04:0a:dc:05:14', '54:04:0a:dc:05:17', '54:04:0a:dc:05:a5', '54:04:0a:dc:05:ae', '54:04:0a:dc:05:b4', '54:04:0a:dc:05:d1', '54:04:0a:dc:05:fd', '54:04:0a:dc:06:5c', '54:04:0a:dc:06:92', '54:04:0a:dc:06:99', '54:04:0a:dc:06:9b', '54:04:0a:dc:07:3f', '54:04:0a:dc:07:5d', '54:04:0a:dc:07:6b', '54:04:0a:dc:07:9e', '54:04:0a:dc:07:aa', '54:04:0a:dc:08:0e', '54:04:0a:dc:08:1c', '54:04:0a:dc:08:48', '54:04:0a:dc:08:52', '54:04:0a:dc:08:5a', '54:04:0a:dc:08:5c', '54:04:0a:dc:08:87', '54:04:0a:dc:08:b6', '54:04:0a:dc:08:ba', '54:04:0a:dc:08:c0', '54:04:0a:dc:08:c2', '54:04:0a:dc:08:da', '54:04:0a:dc:08:ec', '54:04:0a:dc:08:ed', '02:42:c0:dc:08:ef', '54:04:0a:dc:09:59', '54:04:0a:dc:09:64', '54:04:0a:dc:09:77', '54:04:0a:dc:09:7c', '54:04:0a:dc:09:8c', '54:04:0a:dc:09:b8', '54:04:0a:dc:09:9b', '54:04:0a:dc:09:9d', '54:04:0a:dc:09:b2', '02:42:c0:dc:09:c1', '54:04:0a:dc:09:c4', '54:04:0a:dc:09:d4', '54:04:0a:dc:09:d6', '54:04:0a:dc:09:e1', '54:04:0a:dc:09:e4', '54:04:0a:dc:09:eb', '54:04:0a:dc:09:f6', '54:04:0a:dc:09:fa', '54:04:0a:dc:0a:17', '54:04:0a:dc:0a:22', '54:04:0a:dc:0a:25', '54:04:0a:dc:0a:2e', '54:04:0a:dc:0a:34', '54:04:0a:dc:0a:48', '54:04:0a:dc:0a:51', '54:04:0a:dc:0a:5d', '54:04:0a:dc:0a:74', '54:04:0a:dc:0a:76', '54:04:0a:dc:0a:78', '54:04:0a:dc:0a:8f', '54:04:0a:dc:0a:c6', '54:04:0a:dc:0a:cc', '54:04:0a:dc:0a:da', '54:04:0a:dc:0a:e2', '54:04:0a:dc:0a:e6', '54:04:0a:dc:0a:f2', '54:04:0a:dc:0a:f5', '54:04:0a:dc:0a:ff', '54:04:0a:dc:0b:02', '54:04:0a:dc:0b:05', '54:04:0a:dc:0b:0d', '54:04:0a:dc:0b:12', '54:04:0a:dc:0b:26', '54:04:0a:dc:0b:3f', '54:04:0a:dc:0b:45', '54:04:0a:dc:0b:48', '54:04:0a:dc:0b:51', '54:04:0a:dc:0b:54', '54:04:0a:dc:0b:57', '54:04:0a:dc:0b:5d', '54:04:0a:dc:0b:74', '54:04:0a:dc:0b:78', '54:04:0a:dc:0b:81', '54:04:0a:dc:0b:83', '54:04:0a:dc:0b:af', '54:04:0a:dc:0b:b0', '54:04:0a:dc:0b:b5', '54:04:0a:dc:0b:b7', '54:04:0a:dc:0b:b9', '54:04:0a:dc:0b:c1', '54:04:0a:dc:0b:d0', '54:04:0a:dc:0c:11', '54:04:0a:dc:0c:14', '54:04:0a:dc:0c:17', '54:04:0a:dc:0c:1e', '54:04:0a:dc:0c:26', '54:04:0a:dc:0c:2b', '54:04:0a:dc:0c:2d', '54:04:0a:dc:0c:2f', '54:04:0a:dc:0c:34', '54:04:0a:dc:0c:58', '54:04:0a:dc:0c:63', '0c:86:10:7c:60:00', '56:03:02:00:25:06', '56:03:02:00:25:06', '56:03:02:00:25:0d']
ok
test_arp_table_to_json (tests.functional.test_table_present.test_table.test_arp_table_to_json) ... ok
test_table_get_value (tests.functional.test_table_present.test_table.test_table_get_value) ... ok
test_utils_fs_cat (tests.functional.test_utils_file_system.TestUtilsFS.test_utils_fs_cat) ... ok
test_utils_fs_checksum (tests.functional.test_utils_file_system.TestUtilsFS.test_utils_fs_checksum) ... ok
test_utils_fs_cp (tests.functional.test_utils_file_system.TestUtilsFS.test_utils_fs_cp) ... ok
test_utils_fs_ls (tests.functional.test_utils_file_system.TestUtilsFS.test_utils_fs_ls) ... ok
test_utils_fs_mkdir (tests.functional.test_utils_file_system.TestUtilsFS.test_utils_fs_mkdir) ... ok
test_utils_fs_mv (tests.functional.test_utils_file_system.TestUtilsFS.test_utils_fs_mv) ... ok
test_utils_fs_pwd (tests.functional.test_utils_file_system.TestUtilsFS.test_utils_fs_pwd) ... ok
test_utils_fs_rm (tests.functional.test_utils_file_system.TestUtilsFS.test_utils_fs_rm) ... ok
test_utils_fs_rmdir (tests.functional.test_utils_file_system.TestUtilsFS.test_utils_fs_rmdir) ... ok
test_utils_fs_stat (tests.functional.test_utils_file_system.TestUtilsFS.test_utils_fs_stat) ... ok
test_utils_fs_storageUsage (tests.functional.test_utils_file_system.TestUtilsFS.test_utils_fs_storageUsage) ... ok
test_utils_fs_symlink (tests.functional.test_utils_file_system.TestUtilsFS.test_utils_fs_symlink) ... ok
test_u [...]

2024-10-10 08:04 UTC, chidanandpujar commented
UT execution looks good.

(venv) root@masterhost:~/pyez_release_test1/py-junos-eznc/tests/unit# nose2 -v 
test_CommitError_repr (tests.unit.test_exception.Test_RpcError.test_CommitError_repr) ... ok
test_ConfigLoadError_repr (tests.unit.test_exception.Test_RpcError.test_ConfigLoadError_repr) ... ok
test_ConnectError (tests.unit.test_exception.Test_RpcError.test_ConnectError) ... ok
test_ConnectError_msg (tests.unit.test_exception.Test_RpcError.test_ConnectError_msg) ... ok
test_json_error (tests.unit.test_exception.Test_RpcError.test_json_error) ... ok
test_json_error_offending_line (tests.unit.test_exception.Test_RpcError.test_json_error_offending_line) ... ok
test_repr_multi_warning (tests.unit.test_exception.Test_RpcError.test_repr_multi_warning) ... ok
test_rpcerror_jxml_check (tests.unit.test_exception.Test_RpcError.test_rpcerror_jxml_check) ... ok
test_rpcerror_repr (tests.unit.test_exception.Test_RpcError.test_rpcerror_repr) ... ok
test_RpcTimeoutError_repr (tests.unit.test_exception.Test_RpcError.test_RpcTimeoutError_repr) ... ok
test_SwRollbackError_repr (tests.unit.test_exception.Test_RpcError.test_SwRollbackError_repr) ... ok
test_SwRollbackError_repr_multi (tests.unit.test_exception.Test_RpcError.test_SwRollbackError_repr_multi) ... ok
test_domain_fact_from_config (tests.unit.facts.test_domain.TestDomain.test_domain_fact_from_config) ... ok
test_domain_fact_from_file (tests.unit.facts.test_domain.TestDomain.test_domain_fact_from_file) ... ok
test_vc (tests.unit.facts.test_get_virtual_chassis_information.TestGetVirtualChassisInformation.test_vc) ... ok
test_vc_dual_master (tests.unit.facts.test_get_virtual_chassis_information.TestGetVirtualChassisInformation.test_vc_dual_master) ... ok
test_vc_empty (tests.unit.facts.test_get_virtual_chassis_information.TestGetVirtualChassisInformation.test_vc_empty) ... ok
test_vc_error (tests.unit.facts.test_get_virtual_chassis_information.TestGetVirtualChassisInformation.test_vc_error) ... ok
test_vc_mmvc (tests.unit.facts.test_get_virtual_chassis_information.TestGetVirtualChassisInformation.test_vc_mmvc) ... ok
test_vc_mmvcf (tests.unit.facts.test_get_virtual_chassis_information.TestGetVirtualChassisInformation.test_vc_mmvcf) ... ok
test_home_fact (tests.unit.facts.test_file_list.TestFileList.test_home_fact) ... ok
test_home_fact_multi_dir (tests.unit.facts.test_file_list.TestFileList.test_home_fact_multi_dir) ... ok
test_re_info_dual (tests.unit.facts.test_get_route_engine_information.TestGetRouteEngineInformation.test_re_info_dual) ... ok
test_re_info_mx_vc (tests.unit.facts.test_get_route_engine_information.TestGetRouteEngineInformation.test_re_info_mx_vc) ... ok
test_re_info_single (tests.unit.facts.test_get_route_engine_information.TestGetRouteEngineInformation.test_re_info_single) ... ok
test_current_re_fact (tests.unit.facts.test_current_re.TestCurrentRe.test_current_re_fact) ... ok
test_current_re_fact_empty (tests.unit.facts.test_current_re.TestCurrentRe.test_current_re_fact_empty) ... ok
test_current_re_fact_jdm (tests.unit.facts.test_current_re.TestCurrentRe.test_current_re_fact_jdm) ... ok
test_current_re_fact_rpc_error (tests.unit.facts.test_current_re.TestCurrentRe.test_current_re_fact_rpc_error) ... ok
test_current_re_fact_srx_cluster_index_error (tests.unit.facts.test_current_re.TestCurrentRe.test_current_re_fact_srx_cluster_index_error) ... ok
test_current_re_fact_srx_cluster_primary (tests.unit.facts.test_current_re.TestCurrentRe.test_current_re_fact_srx_cluster_primary) ... ok
test_current_re_fact_srx_cluster_primary_id_16 (tests.unit.facts.test_current_re.TestCurrentRe.test_current_re_fact_srx_cluster_primary_id_16) ... 16
ok
test_current_re_fact_srx_cluster_primary_id_255 (tests.unit.facts.test_current_re.TestCurrentRe.test_current_re_fact_srx_cluster_primary_id_255) ... ok
test_current_re_fact_srx_cluster_primary_id_31 (tests.unit.facts.test_current_re.TestCurrentRe.test_current_re_fact_srx_cluster_primary_id_31) ... ok
test_current_re_fact_srx_cluster_secondary (tests.unit.facts.test_current_re.TestCurrentRe.test_current_re_fact_srx_cluster_secondary) ... ok
test_ifd_style_classic (tests.unit.facts.test_ifd_style.TestIfdStyle.test_ifd_style_classic) ... ok
test_ifd_style_None (tests.unit.facts.test_ifd_style.TestIfdStyle.test_ifd_style_None) ... ok
test_ifd_style_switch (tests.unit.facts.test_ifd_style.TestIfdStyle.test_ifd_style_switch) ... ok
test_duplicate_facts (tests.unit.facts.test__init__.TestFactInitialization.test_duplicate_facts) ... ok
test_serialnumber_error_xml (tests.unit.facts.test_get_chassis_inventory.TestChassis.test_serialnumber_error_xml) ... ok
test_serialnumber_fact_from_backplane (tests.unit.facts.test_get_chassis_inventory.TestChassis.test_serialnumber_fact_from_backplane) ... ok
test_serialnumber_fact_from_chassis (tests.unit.facts.test_get_chassis_inventory.TestChassis.test_serialnumber_fact_from_chassis) ... ok
test_serialnumber_not_master (tests.unit.facts.test_get_chassis_inventory.TestChassis.test_serialnumber_not_master) ... ok
test_sw_info_bsys (tests.unit.facts.test_get_software_information.TestGetSoftwareInformation.test_sw_info_bsys) ... ok
test_sw_info_dual (tests.unit.facts.test_get_software_information.TestGetSoftwareInformation.test_sw_info_dual) ... ok
test_sw_info_dual_other_re_off (tests.unit.facts.test_get_software_information.TestGetSoftwareInformation.test_sw_info_dual_other_re_off) ... ok
test_sw_info_err (tests.unit.facts.test_get_software_information.TestGetSoftwareInformation.test_sw_info_err) ... ok
test_sw_info_ex (tests.unit.facts.test_get_software_information.TestGetSoftwareInformation.test_sw_info_ex) ... ok
test_sw_info_gnf (tests.unit.facts.test_get_software_information.TestGetSoftwareInformation.test_sw_info_gnf) ... ok
test_sw_info_jdm (tests.unit.facts.test_get_software_information.TestGetSoftwareInformation.test_sw_info_jdm) ... ok
test_sw_info_nfx (tests.unit.facts.test_get_software_information.TestGetSoftwareInformation.test_sw_info_nfx) ... ok
test_sw_info_no_version (tests.unit.facts.test_get_software_information.TestGetSoftwareInformation.test_sw_info_no_version) ... ok
test_sw_info_simple (tests.unit.facts.test_get_software_information.TestGetSoftwareInformation.test_sw_info_simple) ... ok
test_sw_info_single (tests.unit.facts.test_get_software_information.TestGetSoftwareInformation.test_sw_info_single) ... ok
test_sw_info_srx_cluster (tests.unit.facts.test_get_software_information.TestGetSoftwareInformation.test_sw_info_srx_cluster) ... ok
test_sw_info_txp (tests.unit.facts.test_get_software_information.TestGetSoftwareInformation.test_sw_info_txp) ... ok
test_sw_info_vc (tests.unit.facts.test_get_software_information.TestGetSoftwareInformation.test_sw_info_vc) ... ok
test_srx_cluster_fact_false (tests.unit.facts.test_get_chassis_cluster_status.TestGetChassisClusterStatus.test_srx_cluster_fact_false) ... ok
test_srx_cluster_fact_none (tests.unit.facts.test_get_chassis_cluster_status.TestGetChassisClusterStatus.test_srx_cluster_fact_none) ... ok
test_srx_cluster_fact_true (tests.unit.facts.test_get_chassis_cluster_status.TestGetChassisClusterStatus.test_srx_cluster_fact_true) ... ok
test_srx_cluster_id_fact (tests.unit.facts.test_get_chassis_cluster_status.TestGetChassisClusterStatus.test_srx_cluster_id_fact) ... ok
test_iri_host_to_ip_mapping_fact (tests.unit.facts.test_iri_mapping.TestIriMapping.test_iri_host_to_ip_mapping_fact) ... ok
test_iri_ip_to_host_mapping_fact (tests.unit.facts.test_iri_mapping.TestIriMapping.test_iri_ip_to_host_mapping_fact) ... ok
test_iri_template_host_to_ip_mapping_fact (tests.unit.facts.test_iri_mapping.TestIriMapping.test_iri_template_host_to_ip_mapping_fact) ... ok
test_iri_template_ip_to_host_mapping_fact (tests.unit.facts.test_iri_mapping.TestIriMapping.test_iri_template_ip_to_host_mapping_fact) ... ok
test_emptyget_facts (tests.unit.facts.test_swver.TestVersionInfo.test_emptyget_facts) ... ok
test_version_feature_velocity (tests.unit.facts.test_swver.TestVersionInfo.test_versio [...]

2024-10-14 09:32 UTC, dineshbaburam91 commented
ok to test

2024-10-15 04:00 UTC, chidanandpujar commented
Hi @dkaplan1,
    There were some issues with re-running git workflow after few fixes related Unit Tests failures, so we have committed your code changes as part of pull request https://github.com/Juniper/py-junos-eznc/pull/1334 and verified Unit Tests and Functional Tests, hence closing this pull request as this code is already committed via https://github.com/Juniper/py-junos-eznc/pull/1334.

Thank you

2024-10-15 04:00 UTC, closed without merging